@token = Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiVVNFUiIsInVzZXJJZCI6IjIiLCJlbWFpbCI6Im1hdmFyZ2FzcGVsYWV6QGdtYWlsLmNvbSIsInN1YiI6Im1hdmFyZ2FzcGVsYWV6QGdtYWlsLmNvbSIsImlhdCI6MTc2Mjg5MTgzMywiZXhwIjoxNzYyODk1NDMzfQ.xnUBU6Ev7LTlgCbDCD8XZnMftCDUvzg5ljj3FQF6VU60dk-X3LhMkCK1BDsBDRiB5PqvFF4bvgX1zzrOjnsITg



### 1. Get All Accommodations (Public)
GET http://localhost:8080/api/accommodations?page=0
Content-Type: application/json

### 2. Get Accommodation by ID (Public)
GET http://localhost:8080/api/accommodations/1
Content-Type: application/json


###  3. Create Accommodation with token (Host Only)
POST http://localhost:8080/api/accommodations
Content-Type: application/json
Authorization: {{token}}

{
  "title": "Finca en medellin 2",
  "description": "A comfortable and modern apartment located in the heart of the city.",
  "city": "Medallo",
  "address": "123 Main St, Medallo",
  "latitude": 6.2429,
  "longitude": -75.5812,
  "pricePerNight": 500000.0,
  "maxCapacity": 4,
  "services": ["WiFi", "Air Conditioning", "Kitchen"],
  "mainImage": "www.example.com/photo1.jpg",
  "images": ["www.example.com/photo1.jpg", "www.example.com/photo2.jpg"]
}

### 4. Update Accommodation (HOST only - owner)
PUT http://localhost:8080/api/accommodations/4
Content-Type: application/json
Authorization: {{token}}

{
  "title": "Finca en medellin - Actualizada",
  "description": "An upgraded comfortable and modern apartment located in the heart of the city.",
  "city": "Medellín",
  "address": "123 Main St, Medellín",
  "latitude": 6.2429,
  "longitude": -75.5812,
  "pricePerNight": 600000.0,
  "maxCapacity": 4,
  "services": ["WiFi", "Air Conditioning", "Kitchen", "Pool"],
  "mainImage": "https://example.com/photo1.jpg",
  "images": ["https://example.com/photo1.jpg", "https://example.com/photo2.jpg", "https://example.com/photo3.jpg"]
}


### 5. Delete Accommodation (HOST only - owner)
DELETE http://localhost:8080/api/accommodations/4
Content-Type: application/json
Authorization: {{token}}


### 6. Search Accommodations (Public)
POST http://localhost:8080/api/accommodations/search?page=0
Content-Type: application/json

{
  "city": "Medallo",
  "checkIn": "2025-10-15",
  "checkOut": "2025-10-20",
  "numberOfGuests": 2,
  "minPrice": 100000,
  "maxPrice": 600000,
  "services": ["WiFi", "Kitchen"]
}

### 7. Search Accommodations by City (Public)
POST http://localhost:8080/api/accommodations/search?page=0
Content-Type: application/json

{
  "city": "Medallo"
}

### 8. Search Accommodations by Price Range (Public)
POST http://localhost:8080/api/accommodations/search?page=0
Content-Type: application/json

{
  "minPrice": 100000,
  "maxPrice": 600000
}

### 9. Search Accommodations by Services (Public)
POST http://localhost:8080/api/accommodations/search?page=0
Content-Type: application/json

{
  "services": ["WiFi", "Kitchen"]
}

### 10. get MyAccommodations by Host (HOST only - owner)
GET http://localhost:8080/api/accommodations/host/my-accommodations?page=0
Content-Type: application/json
Authorization: {{token}}


### 11. get accommodations metrics by Host (HOST only - owner)
GET http://localhost:8080/api/accommodations/2/metrics?startDate=2025-01-01&endDate=2025-12-31
content-Type: application/json
Authorization: {{token}}


### 12. get dates unavailable for booking by accommodation id (Public)
GET http://localhost:8080/api/accommodations/dates-unavailable/2
content-Type: application/json



### 14. how much user mark an accommodation as favorite
GET http://localhost:8080/api/accommodations/host/accommodation-favorites/2
Content-Type: application/json
Authorization: {{token}}

### 15. getOneAcommodation by Host (HOST only - owner)
GET http://localhost:8080/api/accommodations/host/2
Content-Type: application/json
Authorization: {{token}}



