@token = Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiVVNFUiIsInVzZXJJZCI6IjMiLCJlbWFpbCI6Im1hdmFycGVsYWV6QGdtYWlsLmNvbSIsInN1YiI6Im1hdmFycGVsYWV6QGdtYWlsLmNvbSIsImlhdCI6MTc2MDExMzQ3MCwiZXhwIjoxNzYwMTE3MDcwfQ.r0_4e5Cl8F_F_OqWj2Ci5ilJuiMeDpsgPNnjo5SZsNxv7v_wX-vpTuSd5UgJ0MdfuqcUNE1ciQAI6vBuVwEtEg


### 1. Create Booking with token

POST http://localhost:8080/api/reservas
Content-Type: application/json
Authorization: {{token}}

{
  "accommodationId": 1,
  "checkIn": "2025-10-15",
  "checkOut": "2025-10-20",
  "numberOfGuests": 2
}

### List Bookings by User with token and optional status filter
GET http://localhost:8080/api/reservas/usuario?status=PENDING&page=0&size=5
Authorization: {{token}}


### List all Bookings by Host with token and optional status filter
GET http://localhost:8080/api/reservas/anfitrion
Authorization:  {{token}}

### List specific bookings and confirmed status by Host with token
GET http://localhost:8080/api/reservas/anfitrion?accommodationId=1&status=CONFIRMED
Authorization:  {{token}}


### Cancel Booking by Id with token
POST http://localhost:8080/api/reservas/1/cancelar
Authorization: {{token}}

