@token = Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiSE9TVCIsInVzZXJJZCI6IjEiLCJlbWFpbCI6Im1pdmFyZ2FzcGVsYWV6QGdtYWlsLmNvbSIsInN1YiI6Im1pdmFyZ2FzcGVsYWV6QGdtYWlsLmNvbSIsImlhdCI6MTc2MDIyNTczMCwiZXhwIjoxNzYwMjI5MzMwfQ.VjUeoeuUkvyQcMnRZ3oJhFPGHhEvENX1XSnqSbx5EiKYhVbt7WjyS61k6KlilMIJKmZTeOzY8BPhe2NTxeF-YQ




### 1. Create Comment for an accommodation
POST http://localhost:8080/api/comments
Content-Type: application/json
Authorization: {{token}}

{
  "bookingId": 2,
  "rating": 4,
  "text": "Great place to stay!"
}

### 2. Get Comments for an accommodation
GET http://localhost:8080/api/comments/accommodation/2?page=0&size=
Content-Type: application/json


### 3. Get Comments by booking ID
GET http://localhost:8080/api/comments/booking/2
Content-Type: application/json
Authorization: {{token}}


### 4. Delete Comment by ID
DELETE http://localhost:8080/api/comments/delete/5
Content-Type: application/json
Authorization: {{token}}


### 5. Reply to a Comment
POST http://localhost:8080/api/comments/reply
Content-Type: application/json
Authorization: {{token}}

{

  "message": "Thank you for your feedback!",
  "commentId": 6
}

### 6. Delete a Reply
DELETE http://localhost:8080/api/comments/host/delete/2
Content-Type: application/json
Authorization: {{token}}