@token = Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiVVNFUiIsInVzZXJJZCI6IjMiLCJlbWFpbCI6Imh1ZXNwZWQxQGdtYWlsLmNvbSIsInN1YiI6Imh1ZXNwZWQxQGdtYWlsLmNvbSIsImlhdCI6MTc2Mjk3NzY0MCwiZXhwIjoxNzYyOTgxMjQwfQ.creShhurg61camc2RH2RI3SAVSTYSd_OoMhEEMSr3Ir6EcBKu-3M7nJt4ZjuCQN3Nctqrt5RJ_a8rawz5ZVLQQ




### 1. Create Comment for an accommodation
POST http://localhost:8080/api/comments
Content-Type: application/json
Authorization: {{token}}

{
  "bookingId": 4,
  "rating": 5,
  "text": "Great place to stay!"
}

### 2. Get Comments for an accommodation
GET http://localhost:8080/api/comments/accommodation/2?page=0&size=
Content-Type: application/json


### 3. Get Comments by booking ID
GET http://localhost:8080/api/comments/booking/2
Content-Type: application/json
Authorization: {{token}}


### 4. Delete Comment by ID
DELETE http://localhost:8080/api/comments/delete/5
Content-Type: application/json
Authorization: {{token}}


### 5. Reply to a Comment
POST http://localhost:8080/api/comments/reply
Content-Type: application/json
Authorization: {{token}}

{

  "message": "Thank you for your feedback!",
  "commentId": 6
}

### 6. Delete a Reply
DELETE http://localhost:8080/api/comments/host/delete/2
Content-Type: application/json
Authorization: {{token}}