@token = Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiSE9TVCIsInVzZXJJZCI6IjIiLCJlbWFpbCI6Im1hdmFyZ2FzcGVsYWV6QGdtYWlsLmNvbSIsInN1YiI6Im1hdmFyZ2FzcGVsYWV6QGdtYWlsLmNvbSIsImlhdCI6MTc2MzA0MTMzOSwiZXhwIjoxNzYzMDQ0OTM5fQ.YrAZPxicMdjv0cd0QGWkfFrAWluDDVKKtQKidXGhXZXumX0bEjzCQxAGIscBfX6tXexRvHaiZybvRdzJY_aWBQ



### 1. Get Favorite Accommodations
GET http://localhost:8080/api/accommodations/favorites?page=0
Content-Type: application/json
Authorization: {{token}}


### 2. Check if Accommodation is Favorite
GET http://localhost:8080/api/accommodations/is-favorite/2
Content-Type: application/json
Authorization: {{token}}

### 3. Add Favorite Accommodation
POST http://localhost:8080/api/accommodations/add-favorite/2
Content-Type: application/json
Authorization: {{token}}


### 4. Remove Favorite Accommodation
DELETE http://localhost:8080/api/accommodations/remove-favorite/2
Content-Type: application/json
Authorization: {{token}}
