@token = Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiVVNFUiIsInVzZXJJZCI6IjIiLCJlbWFpbCI6Im1hdmFyZ2FzcGVsYWV6QGdtYWlsLmNvbSIsInN1YiI6Im1hdmFyZ2FzcGVsYWV6QGdtYWlsLmNvbSIsImlhdCI6MTc2Mjg5MTgzMywiZXhwIjoxNzYyODk1NDMzfQ.xnUBU6Ev7LTlgCbDCD8XZnMftCDUvzg5ljj3FQF6VU60dk-X3LhMkCK1BDsBDRiB5PqvFF4bvgX1zzrOjnsITg




### 5. Get Profile to verify updates
GET http://localhost:8080/api/users/profile
Content-Type: application/json
Authorization: {{token}}


### 6. Update Profile (requires valid JWT)
PUT http://localhost:8080/api/users/profile
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Miguel Angel",
  "lastName": " Vargas Pelae",
  "phoneNumber": "3208499853",
  "bio": "Anfitrión en Medellín",
  "dateBirth": "2005-11-16",
  "photoProfile": "www.miurl.com/mi-foto-profile.jpg"
}



### 8. Change Password (requires valid JWT)
POST http://localhost:8080/api/users/change-password
Content-Type: application/json
Authorization: {{token}}

{
  "currentPassword": "Password123",
  "newPassword": "NewPassword789"
}


### 9. Become host User Account (requires valid JWT)
POST http://localhost:8080/api/users/become-host
Content-Type: application/json
Authorization: {{token}}

### 10. Delete User Account (requires valid JWT)
DELETE http://localhost:8080/api/users/delete-account
Content-Type: application/json
Authorization: {{token}}
