@token = Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiVVNFUiIsInVzZXJJZCI6IjYiLCJlbWFpbCI6Im1pdmFyZ2FzcGVsYWV6QGdtYWlsLmNvbSIsInN1YiI6Im1pdmFyZ2FzcGVsYWV6QGdtYWlsLmNvbSIsImlhdCI6MTc1OTk1MTUwMSwiZXhwIjoxNzU5OTU1MTAxfQ.7HsJERzOtseQs86C5EY1RA6p0FQjfSrTtD8F6__k9LK85ZaSSwIZc37FCx_ui_EU7XSTiaqaQJsc16-i-zCxXg

### 5. User Registration
GET http://localhost:8080/api/users/profile
Content-Type: application/json
Authorization: {{token}}


### 6. User Profile (requires valid JWT)
PUT http://localhost:8080/api/users/profile
Content-Type: application/json
Authorization: {{token}}

{
  "firstName": "Miguel Angel",
  "lastName": "Vargas",
  "phoneNumber": "3208499853",
  "photoProfile": "www.miurl.com/mi-foto-profile.jpg",
}






### 7. Change Password (requires valid JWT)
POST http://localhost:8080/api/users/change-password
Content-Type: application/json
Authorization: {{token}}

{
  "currentPassword": "NewPassword456",
  "newPassword": "NewPassword789"
}
