@token = Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiSE9TVCIsInVzZXJJZCI6IjEiLCJlbWFpbCI6Im1hdmFyZ2FzcGVsYWV6QGdtYWlsLmNvbSIsInN1YiI6Im1hdmFyZ2FzcGVsYWV6QGdtYWlsLmNvbSIsImlhdCI6MTc2MDA2OTQ3NiwiZXhwIjoxNzYwMDczMDc2fQ.MjJ8JzJyk_9La1BDxIT75iKL-pnSDtycipNiUZbRBn2ek6ziCU30vBNG3aKBWrfq84sPoBk1n_NmTLpx2U9HwA

### 5. Get Profile to verify updates
GET http://localhost:8080/api/users/profile
Content-Type: application/json
Authorization: {{token}}


### 6. User Profile (requires valid JWT)
PUT http://localhost:8080/api/users/profile
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Miguel Ángel",
  "lastName": "Vargas",
  "phoneNumber": "3208499853",
  "bio": "Anfitrión en Medellín",
  "dateBirth": "2005-11-16",
  "photoProfile": "www.miurl.com/mi-foto-profile.jpg"
}



### 8. Change Password (requires valid JWT)
POST http://localhost:8080/api/users/change-password
Content-Type: application/json
Authorization: {{token}}

{
  "currentPassword": "Password123",
  "newPassword": "NewPassword789"
}


### 9. Become host User Account (requires valid JWT)
POST http://localhost:8080/api/users/become-host
Content-Type: application/json
Authorization: {{token}}

